Update merge homebrew
Linuxbrew/brew pull request #148
Opened 2016-10-26 20:00 UTC by maxim-belkin

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/brew/pulls) for the same change?

-----

minor improvements preventing merge if there is no "homebrew" or "origin" repo, and also adds an explicit "--no-ff" flag to the `merge`.

2016-10-26 20:12 UTC, sjackman requested changes

2016-10-26 20:12 UTC, sjackman commented on Library/Homebrew/dev-cmd/merge-homebrew.rb
> +    safe_system "git", "merge", "--no-ff", "homebrew/master", "-m", '"Merge branch homebrew/master into linuxbrew/master"'
What situation brought up the need to add `--no-ff`? Do you have your `~/.gitconfig` set up to fast-forward merge?

`'"Merge branch homebrew/master into linuxbrew/master"'`
This doesn't look right. Why both single and double quotes?

2016-10-26 20:12 UTC, sjackman commented on Library/Homebrew/dev-cmd/merge-homebrew.rb
> +    odie "Please add a remote with the name 'origin' in #{Dir.pwd}" unless remotes.include? "origin"
:+1:

2016-10-26 20:14 UTC, maxim-belkin commented on Library/Homebrew/dev-cmd/merge-homebrew.rb
> +    safe_system "git", "merge", "--no-ff", "homebrew/master", "-m", '"Merge branch homebrew/master into linuxbrew/master"'
Without single-double quotes we get: `git merge homebrew/master -m Merge\ branch\ ...`. With single-double quotes we get: `get merge homebrew/master -m "Merge branch ..."`

2016-10-26 20:15 UTC, sjackman commented on Library/Homebrew/dev-cmd/merge-homebrew.rb
> +    safe_system "git", "merge", "--no-ff", "homebrew/master", "-m", '"Merge branch homebrew/master into linuxbrew/master"'
We want the former I believe.

2016-10-26 20:16 UTC, sjackman commented on Library/Homebrew/dev-cmd/merge-homebrew.rb
> +    safe_system "git", "merge", "--no-ff", "homebrew/master", "-m", '"Merge branch homebrew/master into linuxbrew/master"'
Doesn't the latter result in double quotes in the git commit message, or am I wrong?

2016-10-26 20:17 UTC, maxim-belkin commented on Library/Homebrew/dev-cmd/merge-homebrew.rb
> +    safe_system "git", "merge", "--no-ff", "homebrew/master", "-m", '"Merge branch homebrew/master into linuxbrew/master"'
it doesn't because this is how we pass double quotes to the command line

2016-10-26 20:49 UTC, sjackman requested changes

2016-10-26 20:49 UTC, sjackman commented on Library/Homebrew/dev-cmd/merge-homebrew.rb
> +
Please delete this blank line.

2016-10-27 18:22 UTC, sjackman commented
Please squash these two commits. Are you familiar with `git commit --amend` and `git rebase -i`?

2016-10-27 19:35 UTC, maxim-belkin commented
yes, master!

2016-10-27 19:40 UTC, sjackman approved these changes

2016-10-27 19:40 UTC, sjackman commented
Thanks, Maxim.

2016-10-27 19:57 UTC, merged