Add more paths to find the system Glibc
Linuxbrew/brew pull request #166
Opened 2016-11-03 09:30 UTC by LaurentTreguier

I was trying to install Linuxbrew on [Solus OS](https://solus-project.com/), but Linuxbrew didn't seem to find the system Glibc. Apparently Solus keeps `libc.so.6` in `/usr/lib`, which is not a place checked by the `GlibcRequirement` requirement.
Is there a reason for not looking up in `/usr/lib` and `/usr/lib64` ?

2016-11-03 18:04 UTC, sjackman commented
Library files that are necessary for booting the machine are kept in `/lib`. The [Linux file hierarchy standard](http://www.pathname.com/fhs/pub/fhs-2.3.html#LIBESSENTIALSHAREDLIBRARIESANDKERN) indicates that a library named `/lib/libc.so.*` must exist. I'd open an issue upstream with Solus. In the mean time, the workaround is easy enough.
```sh
ln -s /usr/lib/libc.so.6 /lib/
```

2016-11-03 18:43 UTC, LaurentTreguier commented
`libc.so.*` must not exist in `/lib`, it is stated that it's optional :

![capture d ecran de 2016-11-03 19-41-04](https://cloud.githubusercontent.com/assets/7602755/19980245/960b4406-a1fd-11e6-9b9a-cf4882b84707.png)

2016-11-03 19:03 UTC, sjackman commented
> At least one of each of the following filename patterns are required

The spec seems to contradict itself. I'm unsure now if it's required or optional.

If the workaround of creating a symlink works for you, I'd recommend going with that. I'd also suggest opening an issue upstream with Solus.

2016-11-03 19:04 UTC, LaurentTreguier commented
Yes, I'll probably open up an issue upstream.

2016-11-03 19:04 UTC, sjackman commented
Is your `libc.so.6` located in `/usr/lib64` or in `/usr/lib`?

2016-11-03 19:07 UTC, LaurentTreguier commented
Well, `/usr/lib` is a symlink to `/usr/lib64` in Solus it seems. So... it's in both, but technically it's in `/usr/lib64`

2016-11-03 19:57 UTC, sjackman commented
If we still want to merge this PR, I'd be okay with adding `/usr/lib64/libc.so.6` right after `"/lib64/libc.so.6"

2016-11-03 19:58 UTC, sjackman commented on Library/Homebrew/requirements/glibc_requirement.rb
> +    libc = ["/lib/x86_64-linux-gnu/libc.so.6", "/lib64/libc.so.6", "/lib/libc.so.6", "/lib/i386-linux-gnu/libc.so.6", "/lib/arm-linux-gnueabihf/libc.so.6", "/usr/lib64/libc.so.6", "/usr/lib/libc.so.6
Move `/usr/lib64/libc.so.6` immediately after `/lib64/libc.so.6` and remove `/usr/lib/libc.so.6`

2016-11-03 19:59 UTC, sjackman requested changes
Move /usr/lib64/libc.so.6 immediately after /lib64/libc.so.6 and remove /usr/lib/libc.so.6

2017-03-28 05:17 UTC, sjackman commented
Passing on this PR for now.

2017-03-28 05:17 UTC, closed without merging