superenv: fix cc or its variations is not found
Linuxbrew/brew pull request #355
Opened 2017-04-20 06:54 UTC by xu-cheng

When compiling formula inside superenv, if the compiler is from the
gcc formula and `HOMEBREW_CC/HOMEBREW_CXX` are determined as any of
following:
 * cc/cc-{ver}
 * cpp/cpp-{ver}
 * c++/c++-{ver}
 * gcc
 * g++

The `shims/super/linux/cc` will report the compiler is not
found, as gcc is not available in the path. This fixes such issue.

2017-04-20 16:59 UTC, sjackman commented
I haven't experienced this issue myself, and I'm curious as to why not.

2017-04-20 17:02 UTC, sjackman commented
A somewhat related issue. When the user has symlinked for example `/usr/bin/gcc` to `~/.linuxbrew/bin/gcc-4.8` as per the instructions at https://github.com/Linuxbrew/brew/wiki/Symlink-GCC, superenv is not able to find the compiler, as it doesn't look in `~/.linuxbrew/bin`, by design.

2017-04-20 17:04 UTC, xu-cheng commented
My use case is the system gcc is too old. And I use homebrew gcc for everything.

2017-04-20 17:07 UTC, xu-cheng commented
To reproduce this, you need: (a) use homebrew's gcc, for example when system gcc is too old. (b) Superenv's detemine_cc doesn't return `gcc-5`, but rather plain `cc`or other variants.

2017-04-20 17:12 UTC, xu-cheng commented
A different solution would be handling this inside `shims/super/cc`. e.g. appending prefix/bin to path as fallback.

2017-04-20 17:31 UTC, sjackman commented
> To reproduce this, you need: (a) use homebrew's gcc, for example when system gcc is too old. (b) Superenv's detemine_cc doesn't return gcc-5, but rather plain ccor other variants.

If the `gcc` formula is installed, then `determine_cc` returns `gcc-5`, no? Or do you mean before the `gcc` formula is installed?

> A different solution would be handling this inside shims/super/cc. e.g. appending HOMEBREW_PREFIX/bin to ENV["PATH"] as fallback.

I'm leaning toward this solution.

2017-04-23 14:37 UTC, xu-cheng commented
Updated

2017-04-23 18:39 UTC, sjackman requested changes

2017-04-23 18:39 UTC, sjackman commented on Library/Homebrew/shims/linux/super/cc
> +  paths << "#{ENV["HOMEBREW_PREFIX"]}/bin"
`@homebrew_prefix` is initialized by oddly isn't used currently.
```ruby
paths << "#{@homebrew_prefix}/bin"
```

2017-04-23 18:39 UTC, sjackman commented
Looks good to me after this small change.

2017-04-24 05:31 UTC, xu-cheng commented on Library/Homebrew/shims/linux/super/cc
> +  paths << "#{ENV["HOMEBREW_PREFIX"]}/bin"
`@prefix` is a variable inside cmd class. But we are outside cmd class here. Also it seems that `ENV["HOMEBREW_PREFIX"]` is also used other place in this script.

2017-04-25 23:06 UTC, sjackman approved these changes

2017-04-26 00:11 UTC, sjackman commented
With this patch, the `PATH` in `--env=super` is
```
/home/linuxbrew/.linuxbrew/opt/binutils/bin
/usr/bin
/bin
/usr/sbin
/sbin
/home/linuxbrew/.linuxbrew/opt/gcc/bin
/home/linuxbrew/.linuxbrew/bin
```
The brewed executables should have a higher priority than `/usr/bin`, so I'm merging
```ruby
paths.unshift "#{ENV["HOMEBREW_PREFIX"]}/bin"
```

2017-04-26 00:14 UTC, merged

2017-04-26 00:16 UTC, sjackman commented
Merged. Thanks again for your contribution to Linuxbrew, Xu!

2017-04-26 00:17 UTC, sjackman commented
I also committed e2af04a8e139e3d0deda64a796bc9fed1809dcbd
```diff
--- a/Library/Homebrew/shims/linux/super/cc
+++ b/Library/Homebrew/shims/linux/super/cc
@@ -359,7 +359,7 @@ if __FILE__ == $PROGRAM_NAME
     path = Pathname.new(x)
     path.directory? && path.realpath == superbin
   end
-  paths << "#{ENV["HOMEBREW_PREFIX"]}/bin"
+  paths.unshift "#{ENV["HOMEBREW_PREFIX"]}/bin"
   ENV["PATH"] = paths.join(":")
   args << { :close_others => false }
   exec tool, *args
```