Fix handling of 32-bit libs and libs without linked-in libs
Linuxbrew/brew pull request #369
Opened 2017-05-02 18:01 UTC by maxim-belkin

@sjackman

2017-05-02 18:17 UTC, sjackman requested changes

2017-05-02 18:17 UTC, sjackman commented on Library/Homebrew/os/linux/elf.rb
> +      if path.x86_64?
I've created PR https://github.com/Linuxbrew/brew/pull/370 to add `Hardware::CPU.arch`.
I suggest
```diff
-if needed.empty?
+if needed.empty? || path.arch != Hardware::CPU::arch
   @dylibs = []
   return
 end
```

2017-05-02 18:30 UTC, maxim-belkin commented on Library/Homebrew/os/linux/elf.rb
> +      if path.x86_64?
agreed

2017-05-02 18:58 UTC, sjackman requested changes

2017-05-02 18:58 UTC, sjackman commented on Library/Homebrew/os/linux/elf.rb
> +      if needed.empty? || path.arch != Hardware::CPU::arch
I've merged PR https://github.com/Linuxbrew/brew/pull/370 for `Hardware::CPU.arch`

2017-05-02 18:58 UTC, sjackman commented on Library/Homebrew/extend/os/linux/keg_relocate.rb
> +      next if dylibs.nil?
Remove this line.

2017-05-02 19:05 UTC, sjackman commented
Looks good to me. Does it fix the issue of pouring the `go` bottle?

2017-05-02 19:14 UTC, maxim-belkin commented on Library/Homebrew/os/linux/elf.rb
> +      if needed.empty? || path.arch != Hardware::CPU::arch
path.arch fails

2017-05-02 19:29 UTC, maxim-belkin commented
> Looks good to me. Does it fix the issue of pouring the `go` bottle?

Yes, it does!

```
[linuxbrew@a2e874210168] [Tue May 02 19:27:47]
~/.linuxbrew/Library/Homebrew
(master) $ brew install go
==> Downloading https://linuxbrew.bintray.com/bottles/go-1.8.1.x86_64_linux.bottle.tar.gz
Already downloaded: /home/linuxbrew/.cache/Homebrew/go-1.8.1.x86_64_linux.bottle.tar.gz
==> Pouring go-1.8.1.x86_64_linux.bottle.tar.gz
Error: Failure while executing: ["ldd", "/home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/src/debug/elf/testdata/gcc-386-freebsd-exec"] 

[linuxbrew@a2e874210168] [Tue May 02 19:28:07] [Last Exit Code: 1]
~/.linuxbrew/Library/Homebrew
(master) $ git checkout fix-32bit
Switched to branch 'fix-32bit'

[linuxbrew@a2e874210168] [Tue May 02 19:28:12]
~/.linuxbrew/Library/Homebrew
(fix-32bit) $ brew install go
==> Downloading https://linuxbrew.bintray.com/bottles/go-1.8.1.x86_64_linux.bottle.tar.gz
Already downloaded: /home/linuxbrew/.cache/Homebrew/go-1.8.1.x86_64_linux.bottle.tar.gz
==> Pouring go-1.8.1.x86_64_linux.bottle.tar.gz
==> Caveats
A valid GOPATH is required to use the `go get` command.
If $GOPATH is not specified, $HOME/go will be used by default:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/home/linuxbrew/.linuxbrew/opt/go/libexec/bin

==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/go/1.8.1: 7,030 files, 287.0MB

[linuxbrew@a2e874210168] [Tue May 02 19:28:20]
~/.linuxbrew/Library/Homebrew
(fix-32bit) $
```

2017-05-02 19:29 UTC, maxim-belkin commented on Library/Homebrew/os/linux/elf.rb
> +      if needed.empty? || path.arch != Hardware::CPU::arch
disregard the above comment

2017-05-02 19:29 UTC, sjackman approved these changes

2017-05-02 19:30 UTC, sjackman commented
Once CI passes, go ahead and squash and merge.

2017-05-02 20:35 UTC, sjackman commented
🚢

2017-05-02 20:42 UTC, merged

2017-05-02 20:47 UTC, sjackman commented
Thanks, Maxim!

2017-05-03 03:24 UTC, maxim-belkin commented
"Thanks" should go to you, Shaun :)

2017-05-03 05:16 UTC, sjackman commented
Team effort!