Merge homebrew 1.3.0
Linuxbrew/brew pull request #445
Opened 2017-08-01 23:14 UTC by jonchang

Merge branch homebrew/master into linuxbrew/master

Conflicts:
      Library/Homebrew/formula_support.rb
      Library/Homebrew/test/cleanup_spec.rb

2017-08-01 23:18 UTC, sjackman requested changes

2017-08-01 23:18 UTC, sjackman commented on Library/Homebrew/test/cleanup_spec.rb
> +        expect(described_class.unremovable_kegs).to contain_exactly(f1.installed_kegs[0])
This test may fail due to the file system sorting either chronologically or lexicographically. Try
```ruby
expect(described_class.unremovable_kegs).to contain_exactly(f1.installed_kegs.sort_by(&:to_s)[0])
```

2017-08-02 21:38 UTC, jonchang commented
Alright, fixes made. This should be ready to go once 1.2.6 is tagged and we see no issues.

2017-08-03 00:06 UTC, sjackman commented
```
Error: Calling fails_with :llvm is deprecated!
There is no replacement.
/home/ubuntu/brew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb:63:in `<class:Gcc>'
Please report this to the homebrew/core tap!
/usr/bin/gcc: 4.8.4
glibc: N/A
==> FAILED
```
Interesting that this affects CircleCI but not TravisCI, can't say why.
@jonchang Want to submit a PR to Linuxbrew/core to fix it?

2017-08-04 21:50 UTC, sjackman commented
I've opened PR https://github.com/Linuxbrew/homebrew-core/pull/3610 to fix the above error. After that PR is merged, the CI tests for this PR can be retriggered. Assuming they pass, this PR can be merged.

2017-08-04 21:50 UTC, sjackman approved these changes

2017-08-05 00:21 UTC, sjackman commented
Merged. Thanks, Jon!

2017-08-05 00:21 UTC, closed without merging