superenv: actually fix calls to -R
Linuxbrew/brew pull request #446
Opened 2017-08-02 21:33 UTC by jonchang

Previous attempt: https://github.com/Linuxbrew/brew/pull/328

Possible fix for: https://github.com/Homebrew/homebrew-science/pull/6017

2017-08-03 04:16 UTC, rwhogg commented on Library/Homebrew/shims/linux/super/cc
> +      wl   = "-Wl," unless mode == :ld
Can you remove the extra spaces between "wl" and "="?

2017-08-03 04:37 UTC, jonchang commented on Library/Homebrew/shims/linux/super/cc
> +      wl   = "-Wl," unless mode == :ld
This matches the style for the rest of the block so I didn't change it.

2017-08-03 04:53 UTC, rwhogg commented on Library/Homebrew/shims/linux/super/cc
> +      wl   = "-Wl," unless mode == :ld
Ah, yes it does. Works for me 😄

2017-08-03 15:50 UTC, sjackman commented on Library/Homebrew/shims/linux/super/cc
> +      wl   = "-Wl," unless mode == :ld
What's the motivation for using `canonical_path` here? Here's my previous comment on `canonical_path`, which still stands:
https://github.com/Linuxbrew/brew/pull/328#issuecomment-291979672

The error referenced in this issue is
```
shims/linux/super/cc:221:in `keep_orig?': undefined method `start_with?' for nil:NilClass (NoMethodError)
```
https://gist.github.com/ozcan/b5b8f3dd8e9b5dff0c2a066c5a62ef60#file-03-pip-L1505

2017-08-03 15:53 UTC, sjackman commented on Library/Homebrew/shims/linux/super/cc
> +      wl   = "-Wl," unless mode == :ld
Yipes. It looks as though this chunk uses `path`, which is never assigned. Does this work?
```diff
diff --git a/Library/Homebrew/shims/linux/super/cc b/Library/Homebrew/shims/linux/super/cc
index 13b6b502b..647914c7c 100755
--- a/Library/Homebrew/shims/linux/super/cc
+++ b/Library/Homebrew/shims/linux/super/cc
@@ -188,7 +188,7 @@ class Cmd
       args << "-L#{val}" if keep?(path) && @lset.add?(path)
     when /^-R(.+)?/
       # -R is not the correct way to pass rpaths to the linker
-      val  = chuzzle($1) || enum.next
+      path  = chuzzle($1) || enum.next
       wl = "-Wl," unless mode == :ld
       args << "#{wl}-rpath=" if keep?(path)
     else
```

2017-08-03 15:55 UTC, sjackman requested changes
See comments.

2017-08-03 18:59 UTC, jonchang commented
I agree with your suggestion. Comments addressed in a new commit.

2017-08-03 19:02 UTC, sjackman requested changes

2017-08-03 19:02 UTC, sjackman commented on Library/Homebrew/shims/linux/super/cc
> +      wl   = "-Wl," unless mode == :ld
I'm not a fan of this style of indentation. I know nearby code uses it, but I'd rather not propagate it.

2017-08-05 00:06 UTC, sjackman approved these changes

2017-08-05 00:24 UTC, sjackman commented
Merged. Thanks, Jon!

2017-08-05 00:24 UTC, closed without merging