lines_cop.rb: Disable OS.mac? audit for Linuxbrew
Linuxbrew/brew pull request #502
Opened 2017-10-16 21:16 UTC by iMichka

2017-10-16 21:17 UTC, iMichka commented
Since brew 1.3.4, each tile OS.mac? is used, we get the following audit error:
> Don't use OS.mac?; Homebrew/core only supports macOS

This new test only makes sense on mac OS, so we can disable it for Linuxbrew.

2017-10-16 21:29 UTC, iMichka commented
```
Failures:

  1) RuboCop::Cop::FormulaAudit::Miscellaneous When auditing formula with OS.linux? check
     Failure/Error: expect_offense(expected, actual)

       expected: not nil
            got: nil
     # ./test/support/helper/rubocop.rb:5:in `expect_offense'
     # ./test/rubocops/lines_cop_spec.rb:252:in `block (4 levels) in <top (required)>'
     # ./test/rubocops/lines_cop_spec.rb:251:in `each'
     # ./test/rubocops/lines_cop_spec.rb:251:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:96:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
```

2017-10-16 23:50 UTC, sjackman approved these changes

2017-10-16 23:52 UTC, sjackman commented
```
Failures:

  1) Bash every `.sh` file has valid bash syntax
     Failure/Error: expect(path).to have_valid_bash_syntax

       expected that /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/shcmd.sh is a valid Bash file:
       /bin/bash: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/shcmd.sh: No such file or directory
     # ./test/bash_spec.rb:29:in `block (4 levels) in <top (required)>'
     # ./test/bash_spec.rb:25:in `each'
     # ./test/bash_spec.rb:25:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:96:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
```
I believe this failure is intermittent. It depends on the order in which the tests are run. I'm rerunning CircleCI now.

2017-10-17 00:08 UTC, sjackman requested changes

2017-10-17 00:08 UTC, sjackman commented on Library/Homebrew/rubocops/lines_cop.rb
> +          end if OS.mac?
Please add `next unless OS.mac?` after line 77, before the existing `next unless`.

2017-10-17 00:08 UTC, sjackman commented on Library/Homebrew/test/rubocops/lines_cop_spec.rb
> +    end if OS.mac?
Try changing line 229 to
```ruby
it "with OS.linux? check", :needs_macos do
```
I'm not certain that's the correct syntax, but give it a go.

2017-10-17 00:08 UTC, sjackman commented
CircleCI succeeded this time, so it is an intermittent failure.

2017-10-17 06:51 UTC, sjackman commented on Library/Homebrew/rubocops/lines_cop.rb
> +          end if OS.mac?
I turns out that `OS.mac?` is not available inside this function, that is, when running Rubocop. This file is a plugin to Rubocop, and is not run inside the usual Brew environment.

2017-10-17 07:03 UTC, sjackman commented
Supersed by https://github.com/Linuxbrew/brew/pull/503

2017-10-17 07:03 UTC, closed without merging

2017-10-17 11:07 UTC, iMichka commented
Thanks @sjackman