test.rb: Add python to PATH in test env
Linuxbrew/brew pull request #593
Opened 2018-02-07 21:46 UTC by iMichka

Python is now a regular dependency, looking
for it in the requirements does not work anymore.

2018-02-07 22:21 UTC, sjackman commented
How feasible is it to modify the formulae to use `python2` instead of `python`? My guess is not very feasible, but I thought I'd ask.

2018-02-07 22:22 UTC, sjackman commented
Wonder whether the `python` formula should have a `python` executable in `bin` on Linux systems. Unlike on macOS we don't assume that `/usr/bin/python` is in the `PATH`.

2018-02-07 22:22 UTC, sjackman commented
Is this PR addressing a particular build failure, and could you point me to it?

2018-02-07 22:36 UTC, iMichka commented
Not a build failure, a test failure. Python is not in the path during tests. For example `brew test spades` will fail. There are hundreds of other formulae impacted by this.

> I wonder whether the python formula should have a python executable in bin on Linux systems. Unlike on macOS we don't assume that /usr/bin/python is in the PATH.

We could do that. As soon as you put brew first in your path, you sort of "accept" to override stuff. Python is an exception to that list on mac (and all the other keg only stuff), but on Linux we should override python I guess. In march there will be some changes regarding Python3 too, so that `brew install python` will install Python3, so stuff will maybe break again at that time.

2018-02-07 22:42 UTC, sjackman commented
Perhaps we should wait until March then. Let's merge this PR first. I have a small comment.

2018-02-07 22:43 UTC, iMichka commented
Yes, even if it temporary, I would like to get more green tests :) Reading log files is always annoying.

2018-02-07 22:45 UTC, sjackman requested changes

2018-02-07 22:45 UTC, sjackman commented on Library/Homebrew/test.rb
> +    end
```ruby
if formula.deps.map(:&name).include? "python"
  ENV.append_path "PATH", "#{HOMEBREW_PREFIX}/opt/python/libexec/bin"
end
```
A bit more concise and tidy. Totally untested though.

2018-02-08 20:43 UTC, iMichka commented
Ok, I made the change and tested, this works too. I'm fine with that version :)

Can I merge this before 1.5.2? You will need to do the merge again.

2018-02-08 20:46 UTC, sjackman commented
Yes, please merge this PR before 1.5.2. Thanks, Michka!

2018-02-08 20:47 UTC, sjackman approved these changes

2018-02-08 21:01 UTC, closed without merging